sudo: false
language: python

cache:
  directories:
    - $HOME/env

before_install:
  - pip install hererocks
  - hererocks $HOME/env --luajit 2.0.4 --luarocks latest
  - source $HOME/env/bin/activate
  - git clone https://github.com/star-wars-vehicles/gluasrcdiet.git $HOME/gluasrcdiet

install:
  - luarocks install lua-discount
  - luarocks install ldoc
  - cd $HOME/gluasrcdiet
  - luarocks make
  - cd $TRAVIS_BUILD_DIR

before_script:
  - wget -O ldoc.css https://gist.githubusercontent.com/DoctorJew/018661e82c4fb724c48962d8667d27fa/raw/3d1e00522012f87ae8980d07c77a1bbd4cb3d85d/ldoc.css

script:
  - ldoc .
  - mkdir -p ./build/lua;
  - shopt -s globstar;
  - for i in ./lua/**; do
      if [ -f $i ]; then
        outdir=${i#./lua/};
        outdir=${outdir%/*.*};
        mkdir -p ./build/lua/$outdir;
        outfile=./build/lua/$outdir/$(basename $i .lua 2>&1)_.lua;
        echo $i $outfile;
        gluasrcdiet --quiet --none --opt-comments --opt-emptylines $i -o $outfile;
      fi
    done
  - if [ -e ./materials/ ]; then cp -R ./materials/. ./build/materials; fi
  - if [ -e ./models/ ]; then cp -R ./models/. ./build/models; fi
  - if [ -e ./sound/ ]; then cp -R ./sound/. ./build/sound; fi
  - cd ./build;
  - zip -r9 ../star-wars-vehicles-redux.zip * > /dev/null 2>&1;
  - cd $TRAVIS_BUILD_DIR;

after_script:
  - rm -rf ./build

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "star-wars-vehicles-redux.zip"
    skip_cleanup: true
    on:
      tags: true
